# Generated by Django 5.0.2 on 2024-02-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('CreatedAt', models.TimeField()),
            ],
        ),
    ]
